name: "Lint PR title"
# Can run on public GH actions runner
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'main'

permissions: read-all

jobs:
  lint:
    permissions:
      contents: read
    if: ${{ github.head_ref != 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

    - name: Install dependencies
      run: npm install @commitlint/cli @commitlint/config-conventional

    - name: Validate PR title
      run: |
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        echo "$PR_TITLE" | npx commitlint --config commitlint.config.js
